name: Update logs
description: Update test install logs to artifacts

inputs:
  os:
    description: 'The operating system runner'
    required: true

runs:
  using: "composite"
  steps:
    - name: Stage VM logs
      shell: powershell
      if: always()
      run: |
        # Create a directory on the D: drive (the current workspace)
        New-Item -ItemType Directory -Force -Path "vm_logs_staging"
        
        # Copy the log from C: to our D: folder
        if (Test-Path "C:\ProgramData\_VM\log.txt") {
          Copy-Item "C:\ProgramData\_VM\log.txt" -Destination "vm_logs_staging\log.txt"
        }
        
        # Copy the workspace file to the same D: folder
        if (Test-Path "success_failure.json") {
          Copy-Item "success_failure.json" -Destination "vm_logs_staging\"
        }

    - name: Upload VM logs to artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: log-VM-${{ inputs.os }}
        path: vm_logs_staging/ # Now it only looks at one folder on one drive!

    - name: Upload chocolatey logs to artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-choco-${{ inputs.os }}
        path: |
          C:\ProgramData\chocolatey\logs\chocolatey.log
          C:\ProgramData\chocolatey\lib-bad\**\tools\install_log.txt