name: Update logs
description: Update test install logs to artifacts

runs:
  using: "composite"
  steps:
    - name: Upload VM logs to artifacts
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      if: always()
      with:
        name: log-VM-${{ matrix.os }}.zip
        path: |
          C:\ProgramData\_VM\log.txt
          success_failure.json
    - name: Upload chocolatey logs to artifacts
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      if: always()
      with:
        name: logs-choco-${{ matrix.os }}.zip
        path: |
          C:\ProgramData\chocolatey\logs\chocolatey.log
          C:\ProgramData\chocolatey\lib-bad\**\tools\install_log.txt
