name: 🐛 Bug
description: Report that a package is broken or something is not working as expected
labels: [":bug: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting that something is broken in [VM-Packages](https://github.com/mandiant/VM-Packages). Please ensure that there is no [issue](https://github.com/mandiant/VM-Packages/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Anew%3A+package%22) already for this bug. If you know how to solve this problem, please send a pull request! :pray:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: Include the actual and expected behavior. The more details, the better!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. First Step
        2. Second Step
        3. and so on…
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Include the following details about your environment:
        - **Virtualization software**: VMWare, VirtualBox, etc.
        - **VM OS version**: run `(Get-CimInstance Win32_OperatingSystem).version` in Powershell
        - **VM PowerShell version**: run `$PSVersionTable.PSVersion.ToString()` in Powershell
        - **VM Chocolatey version**: run `choco --version`
        - **VM Boxstarter version**: run `choco info -l -r "boxstarter"`
        - **Output of `VM-Get-Host-Info`** that will be available if the `vm.common` package has been install: run `VM-Get-Host-Info` in PowerShell with admin rights
      placeholder: |
        - Virtualization software: 
        - VM OS version: 
        - VM PowerShell version: 
        - VM Chocolatey version: 
        - VM Boxstarter version: 
        - Output of `VM-Get-Host-Info`: 

    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Information
      description: |
        Any additional information, configuration or data that might be necessary to understand and reproduce the issue. For example:
        - Console output
        - The log files `C:\ProgramData\_VM\log.txt` and `C:\ProgramData\chocolatey\logs\chocolatey.log`

        Text logs are preferred over screenshots.
  - type: dropdown
    id: ci
    attributes:
      label: Detected by test suite
      description: Check the [Daily Failures Wiki page](https://github.com/mandiant/VM-Packages/wiki/Daily-Failures) to see if the package failed to install in the latest daily run. **Do not report bugs that are detected by our test suite as we are already aware of them.**
      options:
        - "No"
        - "Yes"
    validations:
      required: true
