name: 🆕 New Package
description: Propose the addition of a new package/tool
title: <package_name>
labels: [":new: package"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to [VM-Packages](https://github.com/mandiant/VM-Packages), your package proposal supports tools available for [FLARE-VM](https://github.com/mandiant/flare-vm)! :cupid: Please ensure that your suggested tool doesn't already exist within the set of [current packages](https://github.com/mandiant/VM-Packages/tree/main/packages) and that there is no [issue](https://github.com/mandiant/VM-Packages/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Anew%3A+package%22) proposal already.
        ### Use the package name as the issue title.
        The convention is to use lowercase names with the following format: `toolname.vm` or `tool-name.vm`. For example `capa.vm` and `fakenet-ng.vm`.
  - type: input
    id: name
    attributes:
      label: Tool Name
      description: The name of the tool being installed, normally different from the package name. For example fakenet-ng.vm (package name) vs FakeNet-NG (tool name).
      placeholder: ex. FakeNet-NG
    validations:
      required: true
  - type: dropdown
    id: category
    validations:
      required: true
    attributes:
      label: Category
      description: Which category should this tool be installed to?
      options:
        - Android
        - Debuggers
        - Delphi
        - Developer Tools
        - Disassemblers
        - dotNet
        - Flash
        - Forensic
        - Hex Editors
        - Java
        - Javascript
        - Net
        - Office
        - PDF
        - Pentest
        - PowerShell
        - Python
        - Text Editors
        - Utilities
        - VB
        - Web Application
  - type: input
    id: url
    attributes:
      label: Download URL
      description: URL to download the tool installer. Use a URL that is not likely to be deleted/unavailable and whose downloaded file is not likely to change as this will eventually break the package.
      placeholder: ex. https://github.com/mandiant/flare-fakenet-ng/releases/download/v1.4.11/fakenet1.4.11.zip
  - type: textarea
    id: why
    attributes:
      label: Why is this tool a good addition?
      description: Tell us why you would like to have this package in FLARE-VM and how this tool is useful for malware analysis, incident response, penetration testing and other security related tasking. Adding new packages involves more maintenance work, tell us what is unique about this tool that can not be done with the current toolset.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
         We really appreciate that you share your package idea with us and we will review your issue as soon as possible. Please understand that our time is limited and we may not be able to create a package for this tool as fast as you may like. To speed up the process, we encourage you to check our [Contributing Wiki page](https://github.com/mandiant/VM-Packages/wiki/Contributing) and send a pull request with the new package. We encourage the community to help us create new packages and to maintain existing ones. Join us! :hugs:
