name: Test NodeJS

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2022
    steps:
      - name: Print NodeJS version
        run: node -v
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build and nodejs.vm
        continue-on-error: true
        env:
          MATRIX_OS: ${{ matrix.os }}
          NODE_OPTIONS: --disable-warning=ExperimentalWarning
        run: scripts/test/test_install.ps1 -package_names "nodejs.vm asar.vm js-beautify.vm js-deobfuscator.vm malware-jail.vm obfuscator-io-deobfuscator.vm pkg-unpacker.vm" -all -max_tries 1
