name: Test

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2022
    steps:
      - name: Print Node version
        run: node -v
      - name: Build and nodejs.vm
        continue-on-error: true
        env:
          MATRIX_OS: ${{ matrix.os }}
        run: scripts/test/test_install.ps1 -package_names "nodejs.vm" -all -max_tries 3
